### ISSUE TITLE
Remove cron library in favour of time.Ticker

### ISSUE THREAD

**Issue by inge4pres** [lastminutedotcom/heimdall#6]
As we only use the cron lib for running a task once every X, we could introduce a `time.Ticker` conigured via the same config options as now.
Using the std lib will make the project lighter and execution should be [much faster from go 1.13](https://github.com/golang/go/issues/27707)

**Comment by ernado** [comment]
New timers will land only to go1.14 :(

Also the cron lib internally [uses the timer.Timer too](https://github.com/robfig/cron/blob/61d93e07d1be270591d43ede700aa3ae69a2326f/cron.go#L186-L224), but with some multiplexing.

**Comment by inge4pres** [comment]
we can keep the library
