### ISSUE TITLE
Metrics are empty

### ISSUE THREAD

**Issue by ludal13** [lastminutedotcom/heimdall#7]
Hi,

I try to use "heimdall" for monitoring my Cloudflare account.
heimdall have been build with last Go version (go version go1.14.2 linux/amd64) and seems fully functionnal.

I have test the three API calls successfully ( but I have a 500 error on some domains).

Here is an example of heimdall's output :

```
INFO[242620] collecting co-location metrics for mydomain.com
INFO[242637] collecting waf trigger metrics for mydomain.com
INFO[242637] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE-ID>/firewall/events?per_page=50
INFO[242637] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE-ID>/firewall/events?per_page=50&next_page_id=<ID>
INFO[242638] waf page: 2
INFO[242638] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE-ID>/firewall/events?per_page=50&next_page_id=<ID>
[...]
INFO[242410] collecting rate limit metrics for mydomain.com
```

Everythings seems fine... but, it seems there is no data inside graphite, but I can see that heimdall has created a "cloudflare" metric name (with the FQDN inside), but metrics are empty.

Unfortunately, I can't see any debug mode that may help me understand what is going one.
Have you any clues that might help me ?

Regards,

**Comment by mad-mags** [comment]
Hi @ludal13,
I'm going to debug your problem, first of all, I would like to upgrade my golang version to 1.14.2, in order to understand if it's a compilation/build issue.

In the meanwhile could you explain to me this sentence: "I have test the three API calls successfully ( but I have a 500 error on some domains)."

Have you tested the call through postman and you received 200 with results but "Heimdall" got a 500?

In this case, could you share the application logs?

**Comment by mad-mags** [comment]
Hi @ludal13,
I tried to build a new version with a new golang version but as I supposed it's work fine.

Could you share the end of the execution log? 
Should be something like this:

```
...
INFO[0080] added metric cloudflare.my_domain.total.requests.http_status.2xx, value 8984, 1587989880 
INFO[0080] added metric cloudflare.my_domain.total.requests.http_status.3xx, value 914, 1587989880 
INFO[0080] added metric cloudflare.my_domain.total.requests.http_status.4xx, value 488, 1587989880 
INFO[0080] added metric cloudflare.my_domain.total.requests.http_status.5xx, value 3, 1587989880 
...
```
in that logs snippet, you can find the print of each single collected metrics

**Comment by ludal13** [comment]
Hi @mad-mags ,

Thank you for your answers !

First, I have to precise that on my Cloudflare, I do have 37 domains, all with the "Entreprise Webiste" plan, but only one have a lot of traffic (let's call it 'domain4.com').

Here is the output when I launch heimdall :

```
$ ~ heimdall
INFO[0000] start collecting data at every 5th minute of the last 5 minute
INFO[0260] collecting co-location metrics for domain1.com
INFO[0262] collecting co-location metrics for domain2.com
INFO[0263] collecting co-location metrics for domain3.com
INFO[0264] collecting co-location metrics for domain4.com
[...]
INFO[0300] collecting waf trigger metrics for domain1.com
INFO[0300] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID_DOMAIN1>/firewall/events?per_page=50
ERRO[0300] ERROR Getting WAF trigger for zone domain1.com, get WAF: HTTP body marshal to JSON error: unexpected end of JSON input
INFO[0300] collecting waf trigger metrics for domain2.com
INFO[0300] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID_DOMAIN2>/firewall/events?per_page=50
ERRO[0301] ERROR Getting WAF trigger for zone domain2.com, get WAF: HTTP body marshal to JSON error: unexpected end of JSON input
INFO[0301] collecting waf trigger metrics for domain3.com
INFO[0301] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID_DOMAIN3>/firewall/events?per_page=50
ERRO[0301] ERROR Getting WAF trigger for zone domain3.com, get WAF: HTTP body marshal to JSON error: unexpected end of JSON input
INFO[0303] collecting waf trigger metrics for domain4.com
INFO[0303] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID_DOMAIN4>/firewall/events?per_page=50
INFO[0303] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID_DOMAIN4>/firewall/events?per_page=50&next_page_id=<ID>
INFO[0303] waf page: 2
INFO[0303] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID_DOMAIN4>/firewall/events?per_page=50&next_page_id=<ID>
[...]
INFO[0358] waf page: 150
INFO[0358] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID_DOMAIN4>/firewall/events?per_page=50&next_page_id=<ID>
```
I have problem getting WAF data for almost all domain, except for the "main one" (domain4.com in this example).
Beside that, it seems the metrics are not collected :/

Regarding your question on the API tests, I just run a curl on the Cloudflare API with the examples available on https://technology.lastminute.com/heimdall-cloudflare-monitor/, and I did receive a 200 OK with datas for all three categories (for my main domain).

1/ co-location metrics
curl -s -X GET "https://api.cloudflare.com/client/v4/zones/<ZONE_ID>/analytics/colos?since=-5&until=-1" -H "X-Auth-Email: <EMAIL>r" -H "X-Auth-Key: <AUTH_KEY>" -H "Content-Type: application/json"

2/ rate limit
curl -s -X GET "https://api.cloudflare.com/client/v4/zones/<ZONE_ID>/security/events?limit=1000&source=rateLimit&since=2020-04-27T11:50:00Z&until=2020-04-27T11:55:00Z" -H "X-Auth-Email: <EMAIL>r" -H "X-Auth-Key: <AUTH_KEY>" -H "Content-Type: application/json"

3/ waf / firewall
curl -s -X GET "https://api.cloudflare.com/client/v4/zones/<ZONE_ID>/firewall/events?per_page=50" -H "X-Auth-Email: <EMAIL>" -H "X-Auth-Key: <AUTH_KEY>" -H "Content-Type: application/json"

On the secondary domains, I do receive an 500 ERROR when I call the WAF / firewall API.

Thanks you.

**Comment by mad-mags** [comment]
Checking my logs is happening also with some our minor domains, seems that the 500 returned was caused by a bad Cloudflare configuration (in my case), try to check your zones configuration.

**Comment by ludal13** [comment]
What kind of "bad configuration" ? I can't see what might be causing these 500 errors.

And are theses 500 errors the main reason why I can't collect metrics ?

**Comment by mad-mags** [comment]
In my case, I delete via terraform the zone, but the zone still exists on Cloudflare but "empty" without any configuration, origin, etc...
When I try to gather data from HTTP calls only for this zone I receive a 500, and the following log:
```
INFO[0045] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE ID>/firewall/events?per_page=50 
ERRO[0045] ERROR Getting WAF trigger for zone <DOMAIN>, get WAF: HTTP body marshal to JSON error: unexpected end of JSON input 
```
 
I don't know if we have the same issue.

Anyway if I understand well you can collect metrics only for the main site () and not for all the others, right?

at the end of the "Heimdall" execution in the log you can find the print of the metrics collected and sent to graphite (is a log similar this ):
```
INFO[0080] added metric cloudflare.my_domain.total.requests.http_status.2xx, value 8984, 1587989880 
INFO[0080] added metric cloudflare.my_domain.total.requests.http_status.3xx, value 914, 1587989880 
INFO[0080] added metric cloudflare.my_domain.total.requests.http_status.4xx, value 488, 1587989880 
INFO[0080] added metric cloudflare.my_domain.total.requests.http_status.5xx, value 3, 1587989880 
```

**Comment by ludal13** [comment]
Mmmn OK for the zone configuration. I will see what I can do.

Otherwise, for the collected metrics, I can confirm you that I am not seeing such lines a the end of the execution of heimdall.
Is there any other log or configuration I could look into ?

**Comment by mad-mags** [comment]
The logical execution of Heimdall is divided into several steps:
1- get zones from your account (no logs for this part)

2- get co-location metrics (you can identify this step through the following log)
```
INFO[0021] collecting co-location metrics for mydomain.com
INFO[0021] collecting co-location metrics for mydomain2.com
etc ...
```

3- get WAF metrics (in order to collect all WAF rules triggered Heimdall can perform up to 150 http calls)
```
INFO[0044] collecting waf trigger metrics for mydomain.com
INFO[0044] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID>/firewall/events?per_page=50 
INFO[0044] calling url: https://api.cloudflare.com/client/v4/zones/<ZONE_ID>/firewall/events?per_page=50&next_page_id=<ID> 
INFO[0045] waf page: 2   
INFO[0044] collecting waf trigger metrics for mydomain2.com
etc ...
```

4- get rate limits
```
INFO[0055] collecting rate limit metrics for mydomain.com
INFO[0056] collecting rate limit metrics for mydomain2.com
```
5- calculate totals by domains (no logs for this part)

6- send all metrics to graphite
```
INFO[0080] added metric cloudflare.mydomain_com.total.requests.http_status.2xx, value 8984, 1587989880 
INFO[0080] added metric cloudflare.mydomain_com.total.requests.http_status.3xx, value 914, 1587989880 
INFO[0080] added metric cloudflare.mydomain_com.total.requests.http_status.4xx, value 488, 1587989880 
INFO[0080] added metric cloudflare.mydomain_com.total.requests.http_status.5xx, value 3, 1587989880 
INFO[0080] added metric cloudflare.mydomain2_com.total.requests.http_status.2xx, value 8984, 1587989880 
INFO[0080] added metric cloudflare.mydomain2_com.total.requests.http_status.3xx, value 914, 1587989880 
INFO[0080] added metric cloudflare.mydomain2_com.total.requests.http_status.4xx, value 488, 1587989880 
INFO[0080] added metric cloudflare.mydomain2_com.total.requests.http_status.5xx, value 3, 1587989880 
etc ...
INFO[0080] added 342 metrics 
```

you could check if in your logs all these steps are present.

**Comment by ludal13** [comment]
Hi,

I've run some more tests, I go through 1 to 5 (included), but I don't have 6.
I don't see my metrics beeing pushed to graphite (but on graphite I do have a cloudflare collection).

Hope it helps...

**Comment by mad-mags** [comment]
Hi,
could you try to copy and paste this test in pkg/metric/adapter_test.go:

```
func Test_sendMetrics(t *testing.T) {
	newGraphite, _ := graphite.NewGraphite("<GRAPHITE_HOST>", <GRAPHITE_PORT>)

	metrics := make([]graphite.Metric, 0)
	for i := 0; i < 100; i++ {
		time.Sleep(1 * time.Second)
		utc, _ := time.LoadLocation("UTC")
		now := time.Now().In(utc)
		now = time.Date(now.Year(), now.Month(), now.Day(), now.Hour(), now.Minute(), now.Second(), 0, now.Location())
		metrics = append(metrics, metric("mydomain.com", "test", strconv.Itoa(i), now))
	}

	newGraphite.SendMetrics(metrics)
}
```

then move to heimdall/pkg/metric directory and run the test: 
```
go test
```

at the end of the test try this curl:

```
http://<GRAPHITE_HOST>/render/?target=cloudflare.mydomain_com.test&from=-1h&until=now&format=json
```

the result should be something like this:

```
[
  {
    "target": "cloudflare.mydomain_com.test",
    "datapoints": [
      [
        null,
        1588145100
      ],
      [
        null,
        1588145160
      ],
      ...
      [
        99.0,
        1588148340
      ],
      [
        66.0,
        1588148400
      ],
      [
        99.0,
        1588148460
      ],
      [
        null,
        1588148520
      ],
      [
        31.0,
        1588148580
      ],
      [
        99.0,
        1588148640
      ]
    ]
  }
]
```

I tried a lot of tests but all seems ok...

If also this test will not be successful, could you send me the entire log file (cleaned by ZONE_ID)?

Thanks

**Comment by ludal13** [comment]
Hi,

I've modify "heimdall/pkg/metrics/adapter_test.go" to add the new function.
And when I launch the "go test" command:

```
# go test
# github.com/lastminutedotcom/heimdall/pkg/metric [github.com/lastminutedotcom/heimdall/pkg/metric.test]
./adapter_test.go:30:20: undefined: graphite
./adapter_test.go:32:20: undefined: graphite
./adapter_test.go:38:60: undefined: strconv
FAIL	github.com/lastminutedotcom/heimdall/pkg/metric [build failed]
```

Thanks.

**Comment by ludal13** [comment]
And just to clarify, the host "graphite" is reachable from the host:

```
$ telnet graphite 2003
Trying 172.18.0.4...
Connected to graphite.
Escape character is '^]'.
^]q

telnet> q
Connection closed.
```

**Comment by mad-mags** [comment]
Sorry, my fault:

add this 2 lines to the imports on top of the heimdall/pkg/metrics/adapter_test.go

```
	"github.com/marpaia/graphite-golang"
	"strconv"
```

I know that the graphite host is reachable :), but I'm trying to understand what is happening

**Comment by inge4pres** [comment]
Hi @ludal13 and thanks for reporting this issue 😄 
Just a silly question: do you have an Enterprise Cloudflare Account? Is this the one configured in Heimdall and used to call the API?
@mad-mags AFAIR the WAF API is only available for Enterprise customer?

**Comment by ludal13** [comment]
Hi @inge4pres,

Yes, I'm using heimdall with an Enterprise Cloudflare Account :)

**Comment by ludal13** [comment]
> Sorry, my fault:
> 
> add this 2 lines to the imports on top of the heimdall/pkg/metrics/adapter_test.go
> 
> ```
> 	"github.com/marpaia/graphite-golang"
> 	"strconv"
> ```
> 
> I know that the graphite host is reachable :), but I'm trying to understand what is happening

Thanks for the update :)
I have added the 2 lines in the import section.

Here what is happening when I launch it:

```
go test
INFO[0000] adapted data to metrics for 10 inputs
PASS
ok  	github.com/lastminutedotcom/heimdall/pkg/metric	100.028s
```

**Comment by inge4pres** [comment]
So to have the ability to reproduce this on our side in a better way, can you please detail the environment used and the test case? Such as:

* graphite version
* install type (container, VM...)
* domain name format (something.TLD or other?)


We are effectively missing a chance to collect an error in `PushMetrics()` so we have added that, can you please rebuild from tip of `master` and see if some ERROR logs will pop up when executing?

**Comment by ludal13** [comment]
Hi @inge4pres ,

Sure, I am using a docker environnement to run Grafana et Graphite:

```
version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: grafana
    #environment:
    ports:
      - 3000:3000
    networks:
      - heimdall
    #mem_limit: 1024m

  graphite:
    image: graphiteapp/graphite-statsd:latest
    restart: always
    container_name: graphite
    ports:
      - 8081:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    networks:
      - heimdall

networks:
  heimdall:
    external: true
```

go version is :

```
$ go version
go version go1.14.2 linux/amd64
```

**Comment by ludal13** [comment]
Oh!
Seems that problem is solved with the last version of heimdall:

```
INFO[0409] added metric cloudflare.domain_tld.total.bandwidth.uncached, value 85124, 1588753800
INFO[0409] added metric cloudflare.domain_tld.total.requests.http_status.2xx, value 9, 1588753800
INFO[0409] added metric cloudflare.domain_tld.total.requests.http_status.3xx, value 2, 1588753800
INFO[0409] added metric cloudflare.domain_tld.total.requests.http_status.4xx, value 0, 1588753800
```

**Comment by mad-mags** [comment]
Great, so can you find the Cloudflare collection filled in your graphite?

**Comment by ludal13** [comment]
Well... no :/
I don't see any datas in graphite now.

I've try to stop graphite: in that case I do see an error message from heimdall indicating that graphite is not recheable.

I also try to remove the cloudflare collections from graphite in order to get a new one. It's working but I don't have any datas in it.

**Comment by inge4pres** [comment]
By chance have you already tried using the pickle port (2004) instead of the plain-text one? I am not an expert on that but might be that the library we are using is not sending plain text but binary?

**Comment by ludal13** [comment]
I just try it, doesn't seems to be working either:

```
ERRO[7013] error converting metrics and sending to Graphite: write tcp 172.18.0.1:57554->172.18.0.4:2004: write: broken pipe
```

But no problem for reaching graphite on this port:

```
telnet 172.18.0.4 2004
Trying 172.18.0.4...
Connected to graphite.
Escape character is '^]'.
^]q

telnet> q
Connection closed.
```

**Comment by inge4pres** [comment]
Well the error `broken pipe` sounds a lot like a network misconfig, I'll try to replicate the same docker-compose stack locally later and run the tests.
You probably can reach the port from your local, but the container does not reach it, what does this option do?

```
networks:
  heimdall:
    external: true
```

**Comment by ludal13** [comment]
The "network" option tells the containers describe in the stack to use a Docker network named "heimdall", which is managed directly on the host, not by docker-compose.

But heimdall is running on the Docker host, not inside a container.
And as far as I can tell with my telnet's tests, I can successfully reach graphite from the Docker host:

```
$ telnet graphite 2002
Trying 172.18.0.4...
Connected to graphite.
Escape character is '^]'.
^]q

telnet> q
Connection closed.
```

**Comment by inge4pres** [comment]
Ok got it, I'll try set that up later and let you know afterwards

**Comment by inge4pres** [comment]
Hi @ludal13 

we were able to replicate your setup, using your docker-compose file and actually we have to thank you because it enabled us to write a contribution guide using that resource.
We also added a config file that we've tested in our local envs and that is working fine from heimdall running locally to graphite running in docker.

We were able to fetch metrics from Cloudflare and push them into graphite, but we didn't use the `grpahite` hostname you were showing earlier.
Can you please try executing the steps listed in https://github.com/lastminutedotcom/heimdall/blob/master/CONTRIBUTING.md#running-the-application-locally and let us know if it works for you?
cheers 😄

**Comment by ludal13** [comment]
Hi @inge4pres ,

Still not working :/
I rebuilt heimdall and the docker stack from scratch. But I still don't have any datas in graphite, despite the fact that the collection are created...

**Comment by inge4pres** [comment]
so if you `exec` into the `graphite` container you have a `cloudflare` folder but nothing below it?

**Comment by ludal13** [comment]
No, I do have several directories in it:

```
docker exec -ti graphite /bin/sh
/ # ls -l /opt/graphite/storage/whisper/cloudflare/
total 144
drwxr-xr-x    3 root     root          4096 May  6 09:53 domain1_com
drwxr-xr-x    3 root     root          4096 May  6 09:53 domain2_com
drwxr-xr-x    3 root     root          4096 May  6 09:53 domain3_com
```

And if I look more into it :

```
/ # tree /opt/graphite/storage/whisper/cloudflare/domain1_com
/opt/graphite/storage/whisper/cloudflare/domain1_com
├── total
│   ├── bandwidth
│   │   ├── all.wsp
│   │   ├── cached.wsp
│   │   └── uncached.wsp
│   └── requests
│       ├── all.wsp
│       ├── cached.wsp
│       ├── http_status
│       │   ├── 2xx.wsp
│       │   ├── 3xx.wsp
│       │   ├── 4xx.wsp
│       │   └── 5xx.wsp
│       └── uncached.wsp
└── www_domain1_com
    └── total
        └── ratelimit
            ├── delete
            │   ├── challenge.wsp
            │   ├── connection_close.wsp
            │   ├── drop.wsp
            │   ├── jschallenge.wsp
            │   └── simulate.wsp
            ├── get
            │   ├── challenge.wsp
            │   ├── connection_close.wsp
            │   ├── drop.wsp
            │   ├── jschallenge.wsp
            │   └── simulate.wsp
            ├── patch
            │   ├── challenge.wsp
            │   ├── connection_close.wsp
            │   ├── drop.wsp
            │   ├── jschallenge.wsp
            │   └── simulate.wsp
            ├── post
            │   ├── challenge.wsp
            │   ├── connection_close.wsp
            │   ├── drop.wsp
            │   ├── jschallenge.wsp
            │   └── simulate.wsp
            └── put
                ├── challenge.wsp
                ├── connection_close.wsp
                ├── drop.wsp
                ├── jschallenge.wsp
                └── simulate.wsp

12 directories, 35 files
```

But, no datas are shown in graphite's webUI, or in grafana's dashboard either.

**Comment by inge4pres** [comment]
Now this looks like a problem in the Grafana config rather than an issue in data colelction...
Check the Grafana datasource config and if it can access graphite

**Comment by ludal13** [comment]
I think it can access graphite: in grafana Cloudflare's dashboard, I can see the list of all domains...

**Comment by x8k** [comment]
Hi ludal13, it seems there's something between the whisper and the Grafana setup.

You can query `whisper` from Graphite web interface or directly from the filesystem with something like `whisper-fetch.py --from=$(date +%s -d "-5 min") /opt/graphite/storage/whisper/cloudflare/domain1_com/total/bandwidth/all.wsp`.

This command fetches the last 5 minutes, but you can navigate in your whisper directory increasing the time range searching metrics.

**Comment by ludal13** [comment]
Hi @stregatto

Thank you for your help !
With the `whisper-fetch.py` command, I manage to see that I do have metrics in graphite:

```
/ # /opt/graphite/bin/whisper-fetch.py --from=1589273168 /opt/graphite/storage/whisper/cloudflare/domain1_com/total/bandwidth/all.wsp
1589273170	None
1589273180	None
1589273190	None
1589273200	None
1589273210	None
1589273220	203066377.000000
1589273230	None
1589273240	None
1589273250	None
1589273260	None
1589273270	None
1589273280	226114311.000000
1589273290	None
1589273300	None
1589273310	None
1589273320	None
1589273330	None
1589273340	203388695.000000
1589273350	None
1589273360	None
1589273370	None
1589273380	None
1589273390	None
1589273400	228437495.000000
1589273410	None
1589273420	None
1589273430	None
1589273440	None
1589273450	None
1589273460	260408581.000000
1589273470	None
1589273480	None
1589273490	None
1589273500	None
1589273510	None
1589273520	232433257.000000
1589273530	None
1589273540	None
1589273550	None
1589273560	None
1589273570	None
1589273580	211445495.000000
1589273590	None
1589273600	None
1589273610	None
1589273620	None
1589273630	None
1589273640	0.000000
1589273650	None
1589273660	None
1589273670	None
1589273680	None
1589273690	None
1589273700	None
1589273710	None
1589273720	None
1589273730	None
1589273740	None
1589273750	None
1589273760	None
1589273770	None
```

But, strange things... I can't see them in graphite's webUI, nor in grafana's dashboard.
Seems related to a graphite problem here ?

**Comment by ludal13** [comment]
OK i found the problem... it seems that graphite default retention is about 6 hours, and the grafana's dashboard default time range is last 12 hours.
If I change the time range from 2 to 6 hours, I now see the datas...
If I select more than 6 jours, no datas at all are shown.

I will update my graphite configuration to have more data retention.

On your side, do you have the same behaviour on grafana's dashboard if the time range is too large compared to the actual datas in graphite ?

**Comment by inge4pres** [comment]
Glad you solved!
We did not observe this behaviour yet but we will keep an eye on what can be improved in the dashboard JSON regarding this.

**Comment by x8k** [comment]
Hi ludal13,
I'm happy you resolved.
