### ISSUE TITLE
Analytics and WAF deprecation, use GraphQL

### ISSUE THREAD

**Issue by inge4pres** [lastminutedotcom/heimdall#9]
**Suggest a new feature!**
What would you want in Heimdall?
GraphQL analytics from Cloudflare

starting from May 31st the current Analytics and WAF APIs will be deprecated by Cloudflare, so we'd need to switch to the GraphQL endpoint to collect our metrics

**Describe the solution you'd like**
Use a GraphQL library (like [this](https://github.com/graphql-go/graphql)) to interact with Cloudflare endpoint

**Comment by mad-mags** [comment]
https://github.com/lastminutedotcom/heimdall/pull/11
